import { Context } from "./contracManagers/context";
import { strictEqual } from "assert";

contract("main", function () {
  let context: Context;

  before(async () => {
    context = await Context.init();
  });

  /**
   * Example keys are generated by Zokrates. The code.
   * ```
   * def main(private field a, field b) -> bool:
   *    return a == b * b
   * ```
   * 
   * proofs are generated by following command.
   * $ zokrates compute-witness -a 64 8
   */
  it("verify", async function () {
    this.timeout(20000);
    const op = await context.main.verify([
      '08',
      '01',
      '0fc262eaee2bf539b7db4bc31c23dac483e7c0dbb7dbdd1824a40a2adf07838fd51c4df26ffeef3568815e789f5bec2b12788e57dfb43834e1f806f81461e08bd2b9db3e1a10d4e5aae45101b65f8a3f88f87414ed05b8332c5cb51e72ff04ff',
      '0b91a527ca5ac5a1d3fba744cdd1179d55ddc303449c69ee2e38a07a41a608fd27f9863e1f73cff8ee464986870fa21007160d784c3c9d3f2db1ad458696ccdfb1ce2fb82347eecb19bb36862413ce4fa41581c7e34d37a1a4fa777d9eac35111142492fc5277710ef0577aa22b4198c861fc42f9741cb495896f6a2a3a33d37cd9113532fcbd09a601aea4da6bb96c50ae67c179ee64240e52905215edd8f9a09b47036b071fe710866975615cad959bf7ef2b9acc8c95071ce9ba84f923a7a',
      '16995a998f718fd60fb20e7d8d15e959e17bdf37db1773d1f603f0017e55a18b79bf21196f3597c914a6908930260fc512e536f56657209042e2605728a8c0143b13378dc79dbcfdb05ee9e3bf8da6df15098f3e8dad5896241ae897599249a8'
    ])
    console.log(op.results[0])
    const s: any = await context.main.getStorage()
    strictEqual(
      s,
      true,
      "result should be stored"
    );
  });


});
