import { Context } from "./contracManagers/context";
import { strictEqual } from "assert";

contract("main", function () {
  let context: Context;

  before(async () => {
    context = await Context.init();
  });

  /**
   * Example keys are generated by Zokrates. The code.
   * ```
   * def main(private field a, field b) -> bool:
   *    return a == b * b
   * ```
   * 
   * proofs are generated by following command.
   * $ zokrates compute-witness -a 64 8
   */
  it("verify", async function () {
    this.timeout(15000);
    //const op = await context.main.pairingCheck([['169d7633e3da4d413bf1918c412fc54c548ddf641a423f47b61ca883c0ba1b85f5ee13dd63d7c1661cc4fe2ca38f00e1065dbcfb2123f8258ae2b3cf92035485f621e55d433b1f251ad37c02ae2b3ec6a1658ae23bbc77649878ec0871a6d8f1','16c58ffdfec9c8b7a4d3826e32a40f99e97bd237067971e474438078e8bca6ccbbee0870bef905972fe879030273dd671116f52efd0f128a0bd6be9042bec761332408e765609caae2b6f7805ab3287143a9bafeb94a7cdd6635fd1ee293c2cf037bef7f92e32e639cd632611077b121db404705da6a507b9b8d8adc08a38eba27b2d31b7b22e95a96e22e26660162d30dd3791f5adb64150c2e7082f23a214b7ef5aa97fd903e648637deb13c156061788756f74b75545c3453e10822012e6a']])
    const op = await context.main.verify([
      '0000000000000000000000000000000000000000000000000000000000000008',
      '0000000000000000000000000000000000000000000000000000000000000001',
      '0fc262eaee2bf539b7db4bc31c23dac483e7c0dbb7dbdd1824a40a2adf07838fd51c4df26ffeef3568815e789f5bec2b12788e57dfb43834e1f806f81461e08bd2b9db3e1a10d4e5aae45101b65f8a3f88f87414ed05b8332c5cb51e72ff04ff',
      '0b91a527ca5ac5a1d3fba744cdd1179d55ddc303449c69ee2e38a07a41a608fd27f9863e1f73cff8ee464986870fa21007160d784c3c9d3f2db1ad458696ccdfb1ce2fb82347eecb19bb36862413ce4fa41581c7e34d37a1a4fa777d9eac35111142492fc5277710ef0577aa22b4198c861fc42f9741cb495896f6a2a3a33d37cd9113532fcbd09a601aea4da6bb96c50ae67c179ee64240e52905215edd8f9a09b47036b071fe710866975615cad959bf7ef2b9acc8c95071ce9ba84f923a7a',
      '16995a998f718fd60fb20e7d8d15e959e17bdf37db1773d1f603f0017e55a18b79bf21196f3597c914a6908930260fc512e536f56657209042e2605728a8c0143b13378dc79dbcfdb05ee9e3bf8da6df15098f3e8dad5896241ae897599249a8'
    ])
    console.log(op.results[0])
    const s: any = await context.main.getStorage()
    console.log(s)
    strictEqual(
      s,
      true,
      "result should be stored"
    );
  });


});
